version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "fastlambda"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-mnjcuoyxvlby"
s3_prefix = "fastlambda"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
